spring:
  application:
    name: acs

server:
  port: ${server_port}
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${registry_url}
  instance:
    preferIpAddress: true

#默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，
#而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。
ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

logging:
  config: classpath:config/logback.xml
  dir: /home/www/webapp/logs/acs
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error #忽略swagger中的错误信息

jdbc:
  global:
    user: ${jdbc_user}
    password: ${jdbc_password}
    poolsize: ${jdbc_poolsize}
    driverClassName: ${jdbc_driverclassName}
    minIdle: ${jdbc_minIdle}
    maxActive: ${jdbc_maxActive}
    maxWait: ${jdbc_maxWait}
    minEictableIdleTimeMillis: ${jdbc_minEictableIdleTimeMillis}
    defaultDatasource: ac
  jdbcConfigInfos:
    - name: ac
      url: ${jdbc_url}
      uniqueResourceName: mysql.ac.write
    - name: lc
      url: ${jdbc_url_lc}
      uniqueResourceName: mysql.lc.write
redis.pool:
  minIdle: 10
  maxIdle: 300
  maxWait: 1000
  testOnReturn: false
  testOnBorrow: false
  timeout: 1000
  maxActive: 300
  redisInfos:
    - name: default
      isdefault: true
      host: ${redis_host}
      port: ${redis_port}
      authKey: ${redis_authKey}
      connectType: single

mongo.pool:
  address: ${mongo_address}
  #replicaSet: reolicaName
  database: ${mongo_database}
  username: ${mongo_username}
  password: ${mongo_password}
  minConnectionsPerHost: ${mongo_min_connections_per_host}
  maxConnectionsPerHost: ${mongo_max_connections_per_host}
  threadsAllowedToBlockForConnectionMultiplier: ${mongo_threads_allowed_to_block_for_connection_multiplier}
  serverSelectionTimeout: ${mongo_server_selection_timeout}
  maxWaitTime: ${mongo_max_wait_time}
  maxConnectionIdleTime: ${mongo_max_connection_idel_time}
  maxConnectionLifeTime: ${mongo_max_connection_life_time}
  connectTimeout: ${mongo_connect_timeout}
  socketTimeout: ${mongo_socket_timeout}
  #socketKeepAlive: false
  sslEnabled: ${mongo_ssl_enabled}
  sslInvalidHostNameAllowed: ${mongo_ssl_invalid_host_name_allowed}
  alwaysUseMBeans: ${mongo_always_use_m_beans}
  heartbeatSocketTimeout: ${mongo_heartbeat_socket_timeout}
  heartbeatConnectTimeout: ${mongo_heartbeat_connect_timeout}
  minHeartbeatFrequency: ${mongo_min_heartbeat_frequency}
  heartbeatFrequency: ${mongo_heartbeat_frequency}
  localThreshold: ${mongo_local_threshold}

#mybatis分页
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# 是否打开swagger
swagger:
  enable: ${swagger_enable}

oss:
  accessKeyId: ZnKvvfgo9oyBGlJW
  accessKeySecret: WlEKUlkulSCJqbDFvZb0VP2QFpEsYl
  endpoint: oss-cn-shenzhen.aliyuncs.com


gysysconfig:
   bucket: ${aliyun.oss.bucket}
   filePath: ${aliyun.oss.file.path}