spring:
  application:
    name: ts

server:
  port: ${server_port}
  #port: 8081
  servlet:
    context-path: /


eureka:
  client:
    serviceUrl:
      defaultZone: http://1921.168.2.191:8888/eureka

logging:
  config: classpath:conf/logback.xml
  dir: /home/www/webapp/logs/ts

# 是否打开swagger
swagger:
  enable: true
