spring:
  application:
    name: acs

server:
  port: ${server_port}
  servlet:
    context-path: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${registry_url}
  instance:
    preferIpAddress: true

#默认为true。如果设置为false，Ribbon将不会从Eureka中获得服务列表，
#而是使用静态配置的服务列表。静态服务列表可使用：<client>.ribbon.listOfServers来指定。
ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

logging:
  config: classpath:config/logback.xml
  dir: /home/www/webapp/logs/acs

jdbc:
  global:
    user: ${jdbc_user}
    password: ${jdbc_password}
    poolsize: ${jdbc_poolsize}
    driverClassName: ${jdbc_driverclassName}
    minIdle: ${jdbc_minIdle}
    maxActive: ${jdbc_maxActive}
    maxWait: ${jdbc_maxWait}
    minEictableIdleTimeMillis: ${jdbc_minEictableIdleTimeMillis}
    defaultDatasource: admin
  jdbcConfigInfos:
    - name: admin
      url: ${jdbc_url}
      uniqueResourceName: mysql.admin.write
redis.pool:
  minIdle: 10
  maxIdle: 300
  maxWait: 1000
  testOnReturn: false
  testOnBorrow: false
  timeout: 1000
  maxActive: 300
  redisInfos:
    - name: default
      isdefault: true
      host: ${redis_host}
      port: ${redis_port}
      authKey: ${redis_authKey}
      connectType: single

#mybatis分页
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

# 是否打开swagger
swagger:
  enable: true